"""
Layer 2 — Pydantic schema injector.

Generates Python file with Pydantic v2 models for every entity from
PRD agent output.  Injected into APIAgent and DBAgent prompts.
"""

from __future__ import annotations

from typing import Any

import structlog

logger = structlog.get_logger(__name__)

# ── Type mappings: PRD field type → Python type ──────────────────────

_PYTHON_TYPE_MAP: dict[str, str] = {
    "string": "str",
    "str": "str",
    "text": "str",
    "email": "str",
    "url": "str",
    "uuid": "uuid.UUID",
    "integer": "int",
    "int": "int",
    "number": "float",
    "float": "float",
    "boolean": "bool",
    "bool": "bool",
    "date": "datetime.date",
    "datetime": "datetime.datetime",
    "array": "list",
    "object": "dict[str, Any]",
    "json": "dict[str, Any]",
}

_FIELD_VALIDATORS: dict[str, str] = {
    "email": "EmailStr",
    "url": "HttpUrl",
}


def _to_pascal_case(name: str) -> str:
    """Convert a name to PascalCase."""
    parts = name.replace("-", "_").split("_")
    return "".join(part.capitalize() for part in parts if part)


def _to_snake_case(name: str) -> str:
    """Convert camelCase or PascalCase to snake_case."""
    import re
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.lower().replace("-", "_")


def _generate_entity_model(entity: dict[str, Any]) -> str:
    """Generate a Pydantic v2 model for a single entity."""
    name = entity.get("name", "Unknown")
    model_name = _to_pascal_case(name)
    fields = entity.get("fields", [])
    description = entity.get("description", f"{model_name} data model")

    lines: list[str] = []
    lines.append(f'class {model_name}(BaseModel):')
    lines.append(f'    """{description}"""')
    lines.append("")

    if not fields:
        lines.append("    pass")
        return "\n".join(lines)

    for field in fields:
        field_name = _to_snake_case(field.get("name", "unknown"))
        field_type = field.get("type", "string").lower()
        field_desc = field.get("description", "")
        is_required = str(field.get("required", "true")).lower() == "true"
        is_nullable = str(field.get("nullable", "false")).lower() == "true"

        # Get Python type
        python_type = _PYTHON_TYPE_MAP.get(field_type, "str")

        # Handle array with item type
        if field_type == "array":
            item_type = field.get("item_type", "str")
            item_python = _PYTHON_TYPE_MAP.get(item_type.lower(), "str")
            python_type = f"list[{item_python}]"

        # Apply nullable/optional
        if is_nullable and not is_required:
            python_type = f"{python_type} | None"
        elif is_nullable:
            python_type = f"{python_type} | None"
        elif not is_required:
            python_type = f"{python_type} | None"

        # Build Field kwargs
        field_kwargs: list[str] = []
        if field_desc:
            field_kwargs.append(f'description="{field_desc}"')

        if not is_required:
            field_kwargs.append("default=None")

        # String constraints
        if field_type in ("string", "str", "text"):
            min_len = field.get("min_length")
            max_len = field.get("max_length")
            if min_len is not None:
                field_kwargs.append(f"min_length={min_len}")
            if max_len is not None:
                field_kwargs.append(f"max_length={max_len}")

        # Numeric constraints
        if field_type in ("integer", "int", "number", "float"):
            ge = field.get("ge")
            le = field.get("le")
            if ge is not None:
                field_kwargs.append(f"ge={ge}")
            if le is not None:
                field_kwargs.append(f"le={le}")

        if field_kwargs:
            kwargs_str = ", ".join(field_kwargs)
            lines.append(f"    {field_name}: {python_type} = Field({kwargs_str})")
        else:
            lines.append(f"    {field_name}: {python_type}")

    # Model config
    lines.append("")
    lines.append('    model_config = {"from_attributes": True}')

    return "\n".join(lines)


def generate_pydantic_schemas(prd_outputs: dict[str, Any]) -> str:
    """Generate Python file with Pydantic v2 models for every entity.

    Args:
        prd_outputs: PRD agent output containing entity definitions.

    Returns:
        Complete Python file content with Pydantic models.
    """
    lines: list[str] = [
        '"""',
        "AUTO-GENERATED by FORGE Layer 2 — Pydantic Schema Injector.",
        "",
        "DO NOT EDIT — regenerated on each build pipeline run.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import datetime",
        "import uuid",
        "from typing import Any",
        "",
        "from pydantic import BaseModel, Field",
        "",
        "",
    ]

    entities = prd_outputs.get("entities", [])

    if not entities:
        lines.append("# No entities defined in PRD outputs")
        lines.append("")

        result = "\n".join(lines)
        logger.info(
            "pydantic_schema_injector.generated",
            entity_count=0,
            output_length=len(result),
        )
        return result

    for i, entity in enumerate(entities):
        model_str = _generate_entity_model(entity)
        lines.append(model_str)
        lines.append("")
        if i < len(entities) - 1:
            lines.append("")

    result = "\n".join(lines)

    logger.info(
        "pydantic_schema_injector.generated",
        entity_count=len(entities),
        output_length=len(result),
    )

    return result
