"""
Layer 2 — Zod schema injector.

Generates TypeScript Zod schemas for every data model derived from
PRD agent's entity definitions.  Injected into ComponentAgent and
PageAgent prompts.
"""

from __future__ import annotations

from typing import Any

import structlog

logger = structlog.get_logger(__name__)

# ── Type mapping: PRD field types → Zod types ────────────────────────

_ZOD_TYPE_MAP: dict[str, str] = {
    "string": "z.string()",
    "str": "z.string()",
    "text": "z.string()",
    "email": "z.string().email()",
    "url": "z.string().url()",
    "uuid": "z.string().uuid()",
    "integer": "z.number().int()",
    "int": "z.number().int()",
    "number": "z.number()",
    "float": "z.number()",
    "boolean": "z.boolean()",
    "bool": "z.boolean()",
    "date": "z.string().datetime()",
    "datetime": "z.string().datetime()",
    "array": "z.array(z.unknown())",
    "object": "z.record(z.unknown())",
    "json": "z.record(z.unknown())",
}


def _to_pascal_case(name: str) -> str:
    """Convert a name to PascalCase."""
    parts = name.replace("-", "_").split("_")
    return "".join(part.capitalize() for part in parts if part)


def _to_camel_case(name: str) -> str:
    """Convert a name to camelCase."""
    pascal = _to_pascal_case(name)
    if not pascal:
        return ""
    return pascal[0].lower() + pascal[1:]


def _generate_entity_schema(entity: dict[str, Any]) -> str:
    """Generate a Zod schema for a single entity."""
    name = entity.get("name", "Unknown")
    schema_name = _to_pascal_case(name)
    fields = entity.get("fields", [])
    description = entity.get("description", "")

    lines: list[str] = []

    # JSDoc comment
    if description:
        lines.append(f"/** {description} */")

    lines.append(f"export const {schema_name}Schema = z.object({{")

    for field in fields:
        field_name = field.get("name", "unknown")
        field_type = field.get("type", "string").lower()
        field_desc = field.get("description", "")
        is_required = str(field.get("required", "true")).lower() == "true"
        is_nullable = str(field.get("nullable", "false")).lower() == "true"

        # Get Zod type
        zod_type = _ZOD_TYPE_MAP.get(field_type, "z.string()")

        # Handle string constraints
        if field_type in ("string", "str", "text"):
            min_len = field.get("min_length")
            max_len = field.get("max_length")
            if min_len is not None:
                zod_type = f"z.string().min({min_len})"
            if max_len is not None:
                if min_len is not None:
                    zod_type = f"z.string().min({min_len}).max({max_len})"
                else:
                    zod_type = f"z.string().max({max_len})"

        # Handle array with item type
        if field_type == "array":
            item_type = field.get("item_type", "unknown")
            item_zod = _ZOD_TYPE_MAP.get(item_type.lower(), "z.unknown()")
            zod_type = f"z.array({item_zod})"

        # Apply nullable/optional modifiers
        if is_nullable:
            zod_type = f"{zod_type}.nullable()"
        if not is_required:
            zod_type = f"{zod_type}.optional()"

        # Build field line
        camel_name = _to_camel_case(field_name)
        comment = f"  // {field_desc}" if field_desc else ""
        lines.append(f"  {camel_name}: {zod_type},{comment}")

    lines.append("});")
    lines.append("")

    # Type inference
    lines.append(
        f"export type {schema_name} = z.infer<typeof {schema_name}Schema>;"
    )

    return "\n".join(lines)


def generate_zod_schemas(prd_outputs: dict[str, Any]) -> str:
    """Generate TypeScript file with Zod schemas for every data model.

    Args:
        prd_outputs: PRD agent outputs containing entity definitions.

    Returns:
        Complete TypeScript file content with Zod schemas.
    """
    lines: list[str] = [
        "// ═══════════════════════════════════════════════════════════════",
        "// AUTO-GENERATED by FORGE Layer 2 — Zod Schema Injector",
        "// DO NOT EDIT — regenerated on each build pipeline run",
        "// ═══════════════════════════════════════════════════════════════",
        "",
        'import { z } from "zod";',
        "",
    ]

    entities = prd_outputs.get("entities", [])

    if not entities:
        # Fallback: extract entities from feature list or other fields
        features = prd_outputs.get("features", [])
        if features:
            lines.append("// No entities defined in PRD — generated from features")
            lines.append("")
            lines.append("export const FeatureSchema = z.object({")
            lines.append("  id: z.string().uuid(),")
            lines.append("  name: z.string().min(1),")
            lines.append("  description: z.string(),")
            lines.append("  enabled: z.boolean().default(true),")
            lines.append("});")
            lines.append("")
            lines.append("export type Feature = z.infer<typeof FeatureSchema>;")
        else:
            lines.append("// No entities found in PRD outputs")

        result = "\n".join(lines)
        logger.info(
            "zod_schema_injector.generated",
            entity_count=0,
            output_length=len(result),
        )
        return result

    for entity in entities:
        schema_str = _generate_entity_schema(entity)
        lines.append(schema_str)
        lines.append("")

    # Generate a union type for all entities
    if len(entities) > 1:
        schema_names = [
            _to_pascal_case(e.get("name", "Unknown")) for e in entities
        ]
        lines.append("// ── Aggregate type ──")
        union = " | ".join(schema_names)
        lines.append(f"export type AnyEntity = {union};")
        lines.append("")

    result = "\n".join(lines)

    logger.info(
        "zod_schema_injector.generated",
        entity_count=len(entities),
        output_length=len(result),
    )

    return result
