"""add user_status index on coherence_reports

Revision ID: 6f2082565f05
Revises: ba38db4904c4
Create Date: 2026-03-31 02:31:51.679371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2082565f05'
down_revision: Union[str, None] = 'ba38db4904c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_coherence_reports_user_status', 'coherence_reports', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coherence_reports_user_status', table_name='coherence_reports')
    # ### end Alembic commands ###
