"""add_annotation_project_resolved_index

Revision ID: a29004bc4c93
Revises: 6f2082565f05
Create Date: 2026-04-02 22:03:17.917829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29004bc4c93'
down_revision: Union[str, None] = '6f2082565f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('css_selector', sa.String(length=1024), nullable=True))
    op.add_column('annotations', sa.Column('session_id', sa.String(length=256), nullable=True))
    op.alter_column('annotations', 'build_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_annotations_project_resolved', 'annotations', ['project_id', 'resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annotations_project_resolved', table_name='annotations')
    op.alter_column('annotations', 'build_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('annotations', 'session_id')
    op.drop_column('annotations', 'css_selector')
    # ### end Alembic commands ###
