"""add missing sandbox_id index on editor_sessions

Revision ID: ba38db4904c4
Revises: d029cdf075df
Create Date: 2026-03-31 01:37:03.810107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba38db4904c4'
down_revision: Union[str, None] = 'd029cdf075df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_editor_sessions_sandbox_id', 'editor_sessions', ['sandbox_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_editor_sessions_sandbox_id', table_name='editor_sessions')
    # ### end Alembic commands ###
