"""initial schema

Revision ID: d029cdf075df
Revises: 
Create Date: 2026-03-31 01:33:56.649287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd029cdf075df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('onboarded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='plan_tier', create_constraint=True), server_default=sa.text("'free'"), nullable=False),
    sa.Column('token_limit_monthly', sa.Integer(), server_default=sa.text('100000'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_providers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.Enum('anthropic', 'openai', 'gemini', 'grok', 'mistral', 'cohere', 'deepseek', 'together', name='provider_name_enum', create_constraint=True), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('key_iv', sa.LargeBinary(), nullable=False),
    sa.Column('key_tag', sa.LargeBinary(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_connected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_providers_user_id', 'ai_providers', ['user_id'], unique=False)
    op.create_index('uq_user_provider', 'ai_providers', ['user_id', 'provider_name'], unique=True)
    op.create_table('idea_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('initial_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='idea_session_status', create_constraint=True), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idea_sessions_user_id', 'idea_sessions', ['user_id'], unique=False)
    op.create_index('ix_idea_sessions_user_status', 'idea_sessions', ['user_id', 'status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'building', 'live', 'error', name='project_status', create_constraint=True), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('framework', sa.Enum('nextjs', 'react_vite', 'remix', 'fastapi_react', name='project_framework', create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_status_updated', 'projects', ['user_id', 'status', sa.text('updated_at DESC')], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chat_role', create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_project_id', 'chat_messages', ['project_id'], unique=False)
    op.create_index('ix_chat_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    op.create_index('ix_chat_messages_user_status', 'chat_messages', ['user_id', 'role'], unique=False)
    op.create_table('ideas',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('idea_session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enhanced_prompt', sa.Text(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_selected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idea_session_id'], ['idea_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ideas_idea_session_id', 'ideas', ['idea_session_id'], unique=False)
    op.create_index('ix_ideas_user_id', 'ideas', ['user_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='pipeline_status', create_constraint=True), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('current_stage', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_runs_project_id', 'pipeline_runs', ['project_id'], unique=False)
    op.create_index('ix_pipeline_runs_user_id', 'pipeline_runs', ['user_id'], unique=False)
    op.create_index('ix_pipeline_runs_user_status', 'pipeline_runs', ['user_id', 'status'], unique=False)
    op.create_table('preview_shares',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index('ix_preview_shares_project_id', 'preview_shares', ['project_id'], unique=False)
    op.create_index('ix_preview_shares_share_token', 'preview_shares', ['share_token'], unique=True)
    op.create_index('ix_preview_shares_user_id', 'preview_shares', ['user_id'], unique=False)
    op.create_table('sandboxes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('warming', 'ready', 'assigned', 'terminating', 'terminated', name='sandbox_status', create_constraint=True), server_default=sa.text("'warming'"), nullable=False),
    sa.Column('vm_id', sa.String(length=256), nullable=True),
    sa.Column('vm_url', sa.String(length=2048), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandboxes_project_id', 'sandboxes', ['project_id'], unique=False)
    op.create_index('ix_sandboxes_status', 'sandboxes', ['status'], unique=False)
    op.create_index('ix_sandboxes_user_id', 'sandboxes', ['user_id'], unique=False)
    op.create_index('ix_sandboxes_user_status', 'sandboxes', ['user_id', 'status'], unique=False)
    op.create_table('agent_outputs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.Enum('prd', 'design_system', 'layout', 'component', 'page', 'api', 'state', 'integration', 'config', 'quality', name='agent_name_enum', create_constraint=True), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='agent_output_status', create_constraint=True), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_outputs_pipeline_run_id', 'agent_outputs', ['pipeline_run_id'], unique=False)
    op.create_index('ix_agent_outputs_user_id', 'agent_outputs', ['user_id'], unique=False)
    op.create_index('ix_agent_outputs_user_status', 'agent_outputs', ['user_id', 'status'], unique=False)
    op.create_table('builds',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'building', 'succeeded', 'failed', name='build_status', create_constraint=True), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('build_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('gate_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('log_url', sa.String(length=2048), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_builds_pipeline_run_id', 'builds', ['pipeline_run_id'], unique=False)
    op.create_index('ix_builds_project_id', 'builds', ['project_id'], unique=False)
    op.create_index('ix_builds_user_id', 'builds', ['user_id'], unique=False)
    op.create_index('ix_builds_user_status', 'builds', ['user_id', 'status'], unique=False)
    op.create_table('editor_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sandbox_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_file_path', sa.String(length=1024), nullable=True),
    sa.Column('open_tabs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_editor_sessions_project_id', 'editor_sessions', ['project_id'], unique=False)
    op.create_index('ix_editor_sessions_user_id', 'editor_sessions', ['user_id'], unique=False)
    op.create_index('ix_editor_sessions_user_status', 'editor_sessions', ['user_id', 'is_active'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('x_pct', sa.Float(), nullable=False),
    sa.Column('y_pct', sa.Float(), nullable=False),
    sa.Column('page_route', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_annotations_build_id', 'annotations', ['build_id'], unique=False)
    op.create_index('ix_annotations_project_id', 'annotations', ['project_id'], unique=False)
    op.create_index('ix_annotations_user_id', 'annotations', ['user_id'], unique=False)
    op.create_table('build_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('file_tree', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('screenshot_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_build_snapshots_build_id', 'build_snapshots', ['build_id'], unique=False)
    op.create_index('ix_build_snapshots_project_id', 'build_snapshots', ['project_id'], unique=False)
    op.create_table('coherence_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'passed', 'failed', 'fixed', name='coherence_status', create_constraint=True), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('issues_found', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('issues_fixed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('all_passed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coherence_reports_build_id', 'coherence_reports', ['build_id'], unique=False)
    op.create_index('ix_coherence_reports_pipeline_run_id', 'coherence_reports', ['pipeline_run_id'], unique=False)
    op.create_index('ix_coherence_reports_project_id', 'coherence_reports', ['project_id'], unique=False)
    op.create_index('ix_coherence_reports_user_id', 'coherence_reports', ['user_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'deploying', 'live', 'failed', 'rolled_back', name='deployment_status', create_constraint=True), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('target', sa.Enum('cloudflare_pages', 'northflank', 'vercel', name='deployment_target', create_constraint=True), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('deploy_log', sa.Text(), nullable=True),
    sa.Column('environment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deployments_build_id', 'deployments', ['build_id'], unique=False)
    op.create_index('ix_deployments_project_id', 'deployments', ['project_id'], unique=False)
    op.create_index('ix_deployments_user_id', 'deployments', ['user_id'], unique=False)
    op.create_index('ix_deployments_user_status', 'deployments', ['user_id', 'status'], unique=False)
    op.create_table('hot_fix_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'applied', 'failed', 'reverted', name='hot_fix_status', create_constraint=True), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('error_input', sa.Text(), nullable=True),
    sa.Column('fix_description', sa.Text(), nullable=True),
    sa.Column('files_changed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hot_fix_records_build_id', 'hot_fix_records', ['build_id'], unique=False)
    op.create_index('ix_hot_fix_records_project_id', 'hot_fix_records', ['project_id'], unique=False)
    op.create_index('ix_hot_fix_records_user_id', 'hot_fix_records', ['user_id'], unique=False)
    op.create_index('ix_hot_fix_records_user_status', 'hot_fix_records', ['user_id', 'status'], unique=False)
    op.create_table('performance_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('route', sa.String(length=512), nullable=False),
    sa.Column('lcp_ms', sa.Float(), nullable=True),
    sa.Column('cls_score', sa.Float(), nullable=True),
    sa.Column('fid_ms', sa.Float(), nullable=True),
    sa.Column('ttfb_ms', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_performance_reports_build_id', 'performance_reports', ['build_id'], unique=False)
    op.create_index('ix_performance_reports_project_id', 'performance_reports', ['project_id'], unique=False)
    op.create_index('ix_performance_reports_user_id', 'performance_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_performance_reports_user_id', table_name='performance_reports')
    op.drop_index('ix_performance_reports_project_id', table_name='performance_reports')
    op.drop_index('ix_performance_reports_build_id', table_name='performance_reports')
    op.drop_table('performance_reports')
    op.drop_index('ix_hot_fix_records_user_status', table_name='hot_fix_records')
    op.drop_index('ix_hot_fix_records_user_id', table_name='hot_fix_records')
    op.drop_index('ix_hot_fix_records_project_id', table_name='hot_fix_records')
    op.drop_index('ix_hot_fix_records_build_id', table_name='hot_fix_records')
    op.drop_table('hot_fix_records')
    op.drop_index('ix_deployments_user_status', table_name='deployments')
    op.drop_index('ix_deployments_user_id', table_name='deployments')
    op.drop_index('ix_deployments_project_id', table_name='deployments')
    op.drop_index('ix_deployments_build_id', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index('ix_coherence_reports_user_id', table_name='coherence_reports')
    op.drop_index('ix_coherence_reports_project_id', table_name='coherence_reports')
    op.drop_index('ix_coherence_reports_pipeline_run_id', table_name='coherence_reports')
    op.drop_index('ix_coherence_reports_build_id', table_name='coherence_reports')
    op.drop_table('coherence_reports')
    op.drop_index('ix_build_snapshots_project_id', table_name='build_snapshots')
    op.drop_index('ix_build_snapshots_build_id', table_name='build_snapshots')
    op.drop_table('build_snapshots')
    op.drop_index('ix_annotations_user_id', table_name='annotations')
    op.drop_index('ix_annotations_project_id', table_name='annotations')
    op.drop_index('ix_annotations_build_id', table_name='annotations')
    op.drop_table('annotations')
    op.drop_index('ix_editor_sessions_user_status', table_name='editor_sessions')
    op.drop_index('ix_editor_sessions_user_id', table_name='editor_sessions')
    op.drop_index('ix_editor_sessions_project_id', table_name='editor_sessions')
    op.drop_table('editor_sessions')
    op.drop_index('ix_builds_user_status', table_name='builds')
    op.drop_index('ix_builds_user_id', table_name='builds')
    op.drop_index('ix_builds_project_id', table_name='builds')
    op.drop_index('ix_builds_pipeline_run_id', table_name='builds')
    op.drop_table('builds')
    op.drop_index('ix_agent_outputs_user_status', table_name='agent_outputs')
    op.drop_index('ix_agent_outputs_user_id', table_name='agent_outputs')
    op.drop_index('ix_agent_outputs_pipeline_run_id', table_name='agent_outputs')
    op.drop_table('agent_outputs')
    op.drop_index('ix_sandboxes_user_status', table_name='sandboxes')
    op.drop_index('ix_sandboxes_user_id', table_name='sandboxes')
    op.drop_index('ix_sandboxes_status', table_name='sandboxes')
    op.drop_index('ix_sandboxes_project_id', table_name='sandboxes')
    op.drop_table('sandboxes')
    op.drop_index('ix_preview_shares_user_id', table_name='preview_shares')
    op.drop_index('ix_preview_shares_share_token', table_name='preview_shares')
    op.drop_index('ix_preview_shares_project_id', table_name='preview_shares')
    op.drop_table('preview_shares')
    op.drop_index('ix_pipeline_runs_user_status', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_user_id', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_project_id', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_ideas_user_id', table_name='ideas')
    op.drop_index('ix_ideas_idea_session_id', table_name='ideas')
    op.drop_table('ideas')
    op.drop_index('ix_chat_messages_user_status', table_name='chat_messages')
    op.drop_index('ix_chat_messages_user_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_project_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_projects_user_status_updated', table_name='projects')
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_idea_sessions_user_status', table_name='idea_sessions')
    op.drop_index('ix_idea_sessions_user_id', table_name='idea_sessions')
    op.drop_table('idea_sessions')
    op.drop_index('uq_user_provider', table_name='ai_providers')
    op.drop_index('ix_ai_providers_user_id', table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_table('users')
    # ### end Alembic commands ###
